language: node_js

# env:
#   - CXX=g++-4.8

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8

# Ubuntu 14.04 Trusty support
dist: trusty

# DOC: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
matrix:
  include:
    - node_js:
      - 4
      - 5
      - 6
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env: COMPILER=g++-4.8
    - node_js:
      - 4
      - 5
      - 6
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - node_js:
      - 4
      - 5
      - 6
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    # TODO: This currently fails:
    # https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540
    # - node_js:
    #   - 4
    #   - 5
    #   - 6
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.6
    #       packages:
    #         - clang-3.6
    #   env: COMPILER=clang++-3.6
    # - node_js:
    #   - 4
    #   - 5
    #   - 6
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7
    #       packages:
    #         - clang-3.7
    #   env: COMPILER=clang++-3.7

install: npm install

notifications:
  email:
    recipients:
      - ibc@aliax.net
    on_success: change
    on_failure: always
