# Just apply Travis-CI for these branches
branches:
  only:
  - master
  - experimental

# Use Ubuntu 14.04 Trusty
dist: trusty

language: node_js

# DOC: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
matrix:
  include:
    - os: osx
      osx_image: xcode8
      node_js: 9
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 && brew install gcc6 && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  - gulp lint:node
  - gulp tidy
  - gulp test

notifications:
  email:
    recipients:
      - ibc@aliax.net
      - jmillan@aliax.net
    on_success: change
    on_failure: always
